import Footer from './_components/navigation/footer'
import Navbar from './_components/navigation/navbar'
import Providers from './_theme/providers'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const revalidate = 300;
export const metadata = {
  title: 'the lazy sundays blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning >
          <body className={`${inter.className} bg-bgprimary text-textprimary sunset-overlook`}>
            <Providers>
              <Navbar />
              <main id='pg-content' className='mb-auto min-h-[calc(100vh-18.75rem)] px-4 pt-5 pb-10 sm:px-14 lg:px-20'>
                {children}
              </main>
              <Footer />
            </Providers>
          </body>
      </html>
  )
}
