import BackToTop from './_components/common/back-to-top'
import Footer from './_components/navigation/footer'
import Navbar from './_components/navigation/navbar'
import Providers from './_theme/providers'
import './globals.css'
import View from "./_components/view-tracking/view"
import {
  bricoGro,
  firaCode,
  libreBask,
  notoColorEmoji,
  notoSansJP,
  publicSans,
} from "./fonts"

export const revalidate = 10;
export const metadata = {
  title: 'the lazy sundays blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning className={`${publicSans.variable} ${notoSansJP.variable} ${libreBask.variable} ${bricoGro.variable} ${firaCode.variable} ${notoColorEmoji.variable}`}>
          <body className={`font-logo bg-bgprimary text-textprimary sunset-overlook`}>
            <Providers>
              <View id="home"/>
              <Navbar />
              <main id='pg-content' className='mb-auto min-h-[calc(100vh-18.75rem)] px-4 pt-5 sm:px-14 lg:px-20'>
                {children}
              </main>
              <BackToTop />
              <Footer />
            </Providers>
          </body>
      </html>
  )
}
